import '../styles/globals.css'
import type { Metadata } from 'next'
import Footer from '@/components/footer/footer'
import Header from '@/components/header/header'
import '@fortawesome/fontawesome-svg-core/styles.css'
// eslint-disable-next-line import/order
import { config } from '@fortawesome/fontawesome-svg-core'
import {AuthContextProvider} from '@/context/Authcontext'

config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
      
        <html lang="en">
          <body>
            <AuthContextProvider>
              <div>
              <Header />
              
              {children}
              
              <Footer />
              </div>
            </AuthContextProvider>

          </body>
        </html>
    </>
  )
}
